/* Bet tracker per sport: /bet-tracker/[slug]
   Per sport: markten (betTypes), statistieken om te volgen (metrics),
   strategietips (tips) en FAQ. Weergave: app/components/SportView.js */

export const SPORT_PAGES = [
  {
    slug: 'voetbal',
    sport: 'Voetbal',
    emoji: '⚽',
    season: 'Augustus – mei',
    seasonNote: 'Eredivisie, Premier League, Champions League en meer',
    name: 'Voetbal bet tracker',
    title: 'Voetbal bet tracker',
    metaTitle: 'Voetbal bet tracker: voetbalbets bijhouden',
    description:
      'Houd je voetbalbets bij en zie per competitie en markt waar je winst maakt: 1X2, Over/Under, BTTS, Asian handicap, betbuilders en combinaties.',
    intro:
      'Voetbal is veruit de populairste sport om op te wedden, met elke week honderden wedstrijden en tientallen markten per wedstrijd. Juist daardoor verlies je snel het overzicht. Met de voetbal bet tracker van TrackMijnBets zie je precies op welke competities en markten je winst maakt.',
    betTypes: [
      { emoji: '🏆', name: '1X2', text: 'Thuis, gelijk of uit: de basis van voetbalwedden. Houd je 1X2-bets apart bij en zie of je beter bent in favorieten of in underdogs.' },
      { emoji: '🥅', name: 'Over/Under goals', text: 'Het aantal doelpunten, zoals Over 2.5. Speelstijl, weer en de stand in de competitie bepalen de lijn. Vergelijk je resultaat per lijn.' },
      { emoji: '🤝', name: 'Beide teams scoren', text: 'Ja of nee op een doelpunt aan beide kanten. Populair, maar de marge verschilt sterk per bookmaker. Je tracker laat zien of het loont.' },
      { emoji: '⚖️', name: 'Asian handicap', text: 'Handicaps met kwartlijnen, halve winst en half verlies. Scherpere odds dan 1X2, maar lastig bij te houden zonder tracker.' },
      { emoji: '🧱', name: 'Betbuilders', text: 'Meerdere selecties binnen één wedstrijd. Leuk, maar bookmakers rekenen er een hogere marge op. Houd ze apart bij om te zien wat ze je kosten.' },
      { emoji: '🔗', name: 'Combinaties', text: 'Meerdere wedstrijden in één bet. Eén fout en alles is weg. Zie in je statistieken of je combi\'s op lange termijn geld opleveren.' },
      { emoji: '🎯', name: 'Doelpuntenmakers', text: 'Eerste, laatste of op elk moment scorende speler. Hoge odds en grote schommelingen: klein inzetten en goed bijhouden.' },
      { emoji: '📅', name: 'Outrights', text: 'Kampioen, degradant of topscorer. Loopt maanden door. Registreer ze als Lopend zodat je openstaande inzet zichtbaar blijft.' },
    ],
    metrics: [
      { emoji: '🌍', name: 'ROI per competitie', text: 'Tag je bets met de competitie. Veel wedders zijn winstgevend in één competitie die ze goed kennen en verliezen op de rest.' },
      { emoji: '📊', name: 'Enkel vs. combinatie', text: 'Vergelijk het rendement van je enkele bets met je combi\'s en betbuilders. Het verschil is vaak groter dan je denkt.' },
      { emoji: '🏠', name: 'Thuis vs. uit', text: 'Wed je vaker op thuisploegen? Kijk of je daar een systematische voorkeur hebt die je geld kost of juist oplevert.' },
      { emoji: '🔴', name: 'Live vs. pre-match', text: 'Live wedden voelt anders dan vooraf. Tag je livebets en zie of je in-play beslissingen net zo goed zijn.' },
      { emoji: '💰', name: 'Resultaat per oddsbereik', text: 'Win je vooral op lage odds en verlies je op hoge? Je statistieken per oddsbereik laten zien waar je voorsprong zit.' },
      { emoji: '🏦', name: 'Resultaat per bookmaker', text: 'Zie per bookmaker je saldo en rendement. Handig om te bepalen waar je het beste je voetbalbets plaatst.' },
    ],
    tips: [
      { title: '🎯 Specialiseer je in een paar competities', text: 'Niemand kent alle competities. Wie zich richt op twee of drie competities, weet meer dan de gemiddelde wedder en vindt sneller foute odds. Je tracker laat per competitie zien of die kennis ook echt winst oplevert.' },
      { title: '🔗 Wees eerlijk over je combinaties', text: 'Een gewonnen combi van odds 12 blijft in je geheugen hangen, de tien verloren combi\'s niet. Juist daarom is bijhouden zo belangrijk. Zet je combi\'s en betbuilders naast je enkele bets en kijk welke echt geld opleveren.' },
      { title: '⚖️ Vergelijk odds voor elke bet', text: 'Het verschil tussen odds van 1.85 en 1.95 lijkt klein, maar over honderden bets is het het verschil tussen winst en verlies. Vergelijk de odds tussen bookmakers, zeker op populaire wedstrijden.' },
    ],
    faq: [
      { q: 'Kan ik betbuilders en combinaties bijhouden?', a: 'Ja. Je kiest de markt Same Game Multi Bet of Multi Bet en vult de totale odds in. De AI screenshot import herkent ze ook.' },
      { q: 'Hoe houd ik Asian handicap bets bij?', a: 'Kies de markt Handicap en vul de uitkomst in, inclusief half gewonnen, push of half verloren. Je winst of verlies wordt automatisch goed berekend.' },
      { q: 'Kan ik zien in welke competitie ik het beste presteer?', a: 'Ja. Geef je bets een tag met de competitie, zoals "Eredivisie" of "Premier League". In de statistieken zie je dan je winst en ROI per tag.' },
      { q: 'Hoe houd ik een bet op de kampioen bij?', a: 'Voer de bet in met de uitkomst Lopend. Pas hem aan zodra de kampioen bekend is. Tot die tijd zie je je openstaande inzet in je overzicht.' },
      { q: 'Hoeveel voetbalbets moet ik bijhouden voor betrouwbare conclusies?', a: 'Hoe meer, hoe beter. Na een paar honderd bets zegt je ROI al veel meer dan na twintig. Kijk per markt pas naar conclusies als je daar genoeg bets op hebt.' },
    ],
    related: ['asian-handicap-uitleg', 'statistieken', 'bets-importeren-met-ai'],
  },
  {
    slug: 'tennis',
    sport: 'Tennis',
    emoji: '🎾',
    season: 'Januari – november',
    seasonNote: 'Grand Slams, ATP, WTA en Challengers',
    name: 'Tennis bet tracker',
    title: 'Tennis bet tracker',
    metaTitle: 'Tennis bet tracker: tennisbets bijhouden',
    description:
      'Houd je tennisbets bij: winnaar, handicap games, set betting en totaal aantal games. Zie per toernooi en ondergrond hoe je presteert.',
    intro:
      'Tennis wordt bijna het hele jaar door gespeeld en kent maar twee uitkomsten per wedstrijd. Dat maakt het populair bij wedders, maar ook verraderlijk: je plaatst al snel honderden bets per seizoen. Met de tennis bet tracker zie je welke markten, toernooien en ondergronden je winst opleveren.',
    betTypes: [
      { emoji: '🏆', name: 'Wedstrijdwinnaar', text: 'De moneyline: wie wint de partij. De meest gespeelde tennismarkt. Houd bij of je vaker wint op favorieten of op underdogs.' },
      { emoji: '➖', name: 'Handicap games', text: 'Een speler krijgt een voorsprong of achterstand in games, zoals -3.5. Interessant bij grote niveauverschillen.' },
      { emoji: '🔢', name: 'Totaal aantal games', text: 'Over/Under op het aantal games in de wedstrijd. Opslagkracht en ondergrond hebben hier veel invloed op.' },
      { emoji: '🎯', name: 'Set betting', text: 'De exacte uitslag in sets, zoals 2-0 of 3-1. Hogere odds, lagere kans. Houd ze apart bij om te zien of ze lonen.' },
      { emoji: '🥇', name: 'Eerste set', text: 'Winnaar of totaal van alleen de eerste set. Handig als je een sterke start of een trage starter verwacht.' },
      { emoji: '💥', name: 'Tiebreak en aces', text: 'Komt er een tiebreak? Hoeveel aces? Specialistische markten die bij grote serveerders interessant kunnen zijn.' },
      { emoji: '🔴', name: 'Livebets', text: 'Tennis leent zich goed voor live wedden, met momentum per game. Tag je livebets om ze los te beoordelen.' },
      { emoji: '🏅', name: 'Toernooiwinnaar', text: 'Outright op de winnaar van een toernooi. Registreer als Lopend en werk bij na de finale.' },
    ],
    metrics: [
      { emoji: '🟫', name: 'ROI per ondergrond', text: 'Gravel, gras en hardcourt spelen compleet anders. Tag je bets met de ondergrond en zie waar jouw inschattingen het beste kloppen.' },
      { emoji: '🏟️', name: 'Grand Slams vs. kleinere toernooien', text: 'Best of five is voorspelbaarder dan best of three. Vergelijk je resultaat op Grand Slams met dat op ATP 250-toernooien.' },
      { emoji: '👤', name: 'ATP vs. WTA', text: 'Veel wedders presteren duidelijk beter bij de mannen of juist bij de vrouwen. Je statistieken per tag laten het zien.' },
      { emoji: '📈', name: 'Favoriet vs. underdog', text: 'Wed je graag op underdogs? Kijk of je ROI bij hoge odds positief is of dat de favorieten je winst opleveren.' },
      { emoji: '🚑', name: 'Opgaves en voids', text: 'Registreer bets die ongeldig zijn verklaard als Void. Zo blijven je win rate en ROI kloppen.' },
      { emoji: '⏱️', name: 'Live vs. pre-match', text: 'Zie of je livebets tijdens een wedstrijd beter of slechter presteren dan je bets van tevoren.' },
    ],
    tips: [
      { title: '🟫 Ondergrond is alles', text: 'Een topspeler op gravel kan op gras gewoon verliezen. Resultaten verschillen sterk per ondergrond en per type toernooi. Tag je bets met de ondergrond, dan zie je in je statistieken waar je voorsprong zit.' },
      { title: '🚑 Ken de opgaveregels van je bookmaker', text: 'Bij de ene bookmaker wordt een bet ongeldig als een speler opgeeft, bij de andere pas na de eerste set of helemaal niet. Registreer zo\'n bet zoals de bookmaker hem afrekent, zodat je statistieken kloppen.' },
      { title: '🔢 Games-markten zijn vaak scherper dan je denkt', text: 'Handicap games en totaal aantal games worden door bookmakers scherp geprijsd. Vergelijk je rendement op deze markten met dat op de winnaar. Vaak blijkt de eenvoudigste markt het beste te werken.' },
    ],
    faq: [
      { q: 'Hoe registreer ik een bet bij een opgave?', a: 'Wordt de bet door de bookmaker ongeldig verklaard, kies dan de uitkomst Void. Je inzet telt dan niet mee in je winst of verlies.' },
      { q: 'Kan ik mijn tennisbets per ondergrond bekijken?', a: 'Ja. Geef je bets een tag zoals "Gravel", "Gras" of "Hardcourt". In de statistieken zie je je resultaat per tag.' },
      { q: 'Hoe houd ik set betting bij?', a: 'Kies de sport Tennis, vul bij de markt "Set betting" in en als selectie de uitslag, bijvoorbeeld "Alcaraz 3-1".' },
      { q: 'Werkt de screenshot import ook voor tennisbets?', a: 'Ja. Upload een screenshot van je betslip en de AI leest de spelers, markt, odds en inzet uit.' },
      { q: 'Kan ik livebets apart bekijken?', a: 'Ja. Tag je livebets met bijvoorbeeld "Live" en vergelijk in de statistieken je resultaat met je andere bets.' },
    ],
    related: ['statistieken', 'bets-bijhouden', 'odds-vergelijker'],
  },
  {
    slug: 'basketbal',
    sport: 'Basketbal',
    emoji: '🏀',
    season: 'Oktober – juni',
    seasonNote: 'NBA, EuroLeague en BNXT League',
    name: 'Basketbal bet tracker',
    title: 'Basketbal bet tracker',
    metaTitle: 'Basketbal bet tracker: NBA bets bijhouden',
    description:
      'Houd je basketbalbets bij, van NBA tot EuroLeague: moneyline, point spread, totals en player props. Zie per markt je rendement.',
    intro:
      'Bij basketbal draait het om spreads en totals, met odds rond de 1.90 aan beide kanten. Kleine verschillen in odds en lijnen maken daardoor een groot verschil. Met de basketbal bet tracker zie je of jouw aanpak op lange termijn werkt.',
    betTypes: [
      { emoji: '🏆', name: 'Moneyline', text: 'Welk team wint, inclusief verlenging. Bij grote favorieten lage odds, dus kijk goed of het rendement het waard is.' },
      { emoji: '📏', name: 'Point spread', text: 'De handicap in punten, zoals -6.5. De belangrijkste basketbalmarkt. Een halve punt kan het verschil maken.' },
      { emoji: '🔢', name: 'Totals', text: 'Over/Under op het totaal aantal punten. Tempo, blessures en back-to-backs hebben veel invloed op de lijn.' },
      { emoji: '⛹️', name: 'Player props', text: 'Punten, rebounds, assists of 3-pointers van een speler. Een enorme markt met veel keuze. Houd per type prop bij hoe je scoort.' },
      { emoji: '⏱️', name: 'Kwarten en helften', text: 'Spread, total of winnaar per kwart of helft. Handig als je een sterke start of een zwakke bank verwacht.' },
      { emoji: '👥', name: 'Team totals', text: 'Het aantal punten van één team. Minder afhankelijk van de tegenstander dan de gewone total.' },
      { emoji: '🧱', name: 'Same game parlays', text: 'Combinaties binnen één wedstrijd, zoals een speler-prop plus de winnaar. Hogere marge, dus bijhouden is extra belangrijk.' },
      { emoji: '📅', name: 'Futures', text: 'Kampioen, MVP of aantal overwinningen in het seizoen. Registreer als Lopend en werk bij aan het einde van het seizoen.' },
    ],
    metrics: [
      { emoji: '🎯', name: 'Win rate op spreads', text: 'Bij odds van 1.90 heb je een win rate van ruim 52,6% nodig om quitte te spelen. Je tracker laat zien of je daar boven zit.' },
      { emoji: '🏀', name: 'NBA vs. Europees basketbal', text: 'Europese competities worden minder scherp geprijsd dan de NBA. Tag je bets per competitie en vergelijk.' },
      { emoji: '⛹️', name: 'ROI per type prop', text: 'Ben je goed in punten-props maar verlies je op rebounds? Houd het prop-type bij in je markt of tag.' },
      { emoji: '🏠', name: 'Favoriet vs. underdog op de spread', text: 'Leg je vaak punten op favorieten? Kijk of je betere resultaten haalt met de underdog en de punten erbij.' },
      { emoji: '😴', name: 'Back-to-backs', text: 'Teams die de tweede avond op rij spelen, presteren vaak minder. Tag die bets om te zien of je er voordeel uit haalt.' },
      { emoji: '💰', name: 'Resultaat per bookmaker', text: 'Lijnen verschillen per bookmaker. Zie waar je het meeste rendement haalt op je basketbalbets.' },
    ],
    tips: [
      { title: '📏 Elke halve punt telt', text: 'Bij spreads en totals kan een halve punt het verschil zijn tussen winst en verlies, of een push. Vergelijk lijnen tussen bookmakers voordat je een bet plaatst. Over een heel seizoen scheelt dat veel.' },
      { title: '🏥 Blessurenieuws verandert alles', text: 'Het uitvallen van één sterspeler verschuift de lijn met punten. Wie snel reageert op nieuws, vindt waarde voordat de odds zijn aangepast. Tag bets die je op nieuws plaatst en kijk of die strategie werkt.' },
      { title: '🧮 Reken met je break-even', text: 'Bij odds rond de 1.90 is 52,6% de grens. Kijk in je statistieken naar je win rate per markt en vergelijk die met je gemiddelde odds. Zo weet je precies waar je winst maakt.' },
    ],
    faq: [
      { q: 'Telt de verlenging mee?', a: 'Bij de meeste basketbalmarkten wel, maar controleer de regels van je bookmaker. Voer in TrackMijnBets gewoon de uitkomst in zoals de bookmaker die afrekent.' },
      { q: 'Hoe houd ik een push bij?', a: 'Eindigt een spread of total precies op de lijn, dan krijg je je inzet terug. Kies dan de uitkomst Void of Push, zodat de bet niet meetelt in je resultaat.' },
      { q: 'Kan ik player props bijhouden?', a: 'Ja. Vul bij de markt het type prop in, zoals "Points" of "Rebounds", en je selectie, bijvoorbeeld "Over 24.5".' },
      { q: 'Kan ik NBA en EuroLeague apart bekijken?', a: 'Ja. Geef je bets een tag met de competitie en bekijk in de statistieken je resultaat per tag.' },
      { q: 'Hoe houd ik een bet op de NBA-kampioen bij?', a: 'Voer de bet in met de uitkomst Lopend en werk hem bij na de finale. Tot dan zie je je openstaande inzet in je overzicht.' },
    ],
    related: ['statistieken', 'odds-vergelijker', 'calculators'],
  },
  {
    slug: 'darts',
    sport: 'Darts',
    emoji: '🎯',
    season: 'Januari – december',
    seasonNote: 'Premier League, WK, World Matchplay en Pro Tour',
    name: 'Darts bet tracker',
    title: 'Darts bet tracker',
    metaTitle: 'Darts bet tracker: dartsbets bijhouden',
    description:
      'Houd je dartsbets bij: winnaar, handicap legs, totaal aantal 180\'s en hoogste finish. Zie per toernooi en markt hoe je ervoor staat.',
    intro:
      'Darts is in Nederland razend populair, van de Premier League tot het WK in Ally Pally. Er worden het hele jaar door toernooien gespeeld, met veel specifieke markten. Met de darts bet tracker houd je al je dartsbets overzichtelijk bij en zie je waar je voorsprong zit.',
    betTypes: [
      { emoji: '🏆', name: 'Wedstrijdwinnaar', text: 'Wie wint de partij. De meest gespeelde dartsmarkt. Zie of je beter scoort op favorieten of op verrassingen.' },
      { emoji: '➖', name: 'Handicap legs of sets', text: 'Een speler krijgt een voorsprong of achterstand, zoals -2.5 legs. Interessant bij duidelijke niveauverschillen.' },
      { emoji: '🔢', name: 'Totaal aantal legs', text: 'Over/Under op het aantal legs. Hangt sterk af van hoe gelijkwaardig de spelers zijn.' },
      { emoji: '💯', name: '180\'s', text: 'Totaal aantal 180\'s in de wedstrijd of per speler. Een van de populairste specials bij darts.' },
      { emoji: '✅', name: 'Hoogste checkout', text: 'Hoogste finish in de wedstrijd, zoals Over 100.5. Hoge odds en grote schommelingen.' },
      { emoji: '🎯', name: 'Correcte score', text: 'De exacte uitslag in legs of sets. Lage kans, hoge odds. Houd ze apart bij om te zien of ze lonen.' },
      { emoji: '⚡', name: 'Meeste 180\'s', text: 'Welke speler gooit de meeste 180\'s. Een eigen markt met andere kansen dan de winnaar.' },
      { emoji: '🏅', name: 'Toernooiwinnaar', text: 'Outright op de winnaar van het WK of de Premier League. Registreer als Lopend tot de finale.' },
    ],
    metrics: [
      { emoji: '📏', name: 'Kort vs. lang format', text: 'Een wedstrijd over zes legs is veel onvoorspelbaarder dan een WK-partij in sets. Tag je bets met het format en vergelijk.' },
      { emoji: '🏟️', name: 'ROI per toernooi', text: 'Premier League, Pro Tour of WK: zie per toernooi waar jouw kennis de meeste winst oplevert.' },
      { emoji: '💯', name: 'Specials vs. winnaar', text: 'Vergelijk je resultaat op 180\'s en checkouts met je bets op de winnaar. Specials voelen slim, maar lonen ze ook?' },
      { emoji: '📈', name: 'Favoriet vs. underdog', text: 'Darts kent veel verrassingen. Kijk of je ROI hoger is op underdogs of op favorieten.' },
      { emoji: '🧮', name: 'Gemiddelde odds', text: 'Houd je gemiddelde odds in de gaten. Een hoge win rate op lage odds kan alsnog verlies betekenen.' },
      { emoji: '🏦', name: 'Resultaat per bookmaker', text: 'Specials worden per bookmaker heel verschillend geprijsd. Zie waar je het beste je dartsbets plaatst.' },
    ],
    tips: [
      { title: '📏 Let op het format', text: 'Hoe korter de wedstrijd, hoe groter de kans op een verrassing. Op een vloertoernooi over zes legs kan iedereen winnen. Tag je bets met het toernooi of het format om te zien waar je het beste presteert.' },
      { title: '📊 Gebruik gemiddelden, niet namen', text: 'Bekende namen worden vaak te laag geprijsd, spelers in vorm juist te hoog. Wie naar recente gemiddelden en checkout-percentages kijkt, vindt sneller waarde. Houd bij of die aanpak je winst oplevert.' },
      { title: '💯 Wees voorzichtig met specials', text: '180\'s en checkouts zijn leuke markten, maar de marge is vaak hoger. Houd ze apart bij en vergelijk ze met je gewone bets. Zo weet je of je er echt goed in bent.' },
    ],
    faq: [
      { q: 'Kan ik 180\'s-bets bijhouden?', a: 'Ja. Kies de sport Darts, vul bij de markt bijvoorbeeld "180\'s" in en je selectie, zoals "Over 6.5".' },
      { q: 'Hoe houd ik een WK-winnaar bet bij?', a: 'Voer de bet in met de uitkomst Lopend en werk hem bij na de finale. Je openstaande inzet blijft zichtbaar in je overzicht.' },
      { q: 'Kan ik zien op welk toernooi ik het beste presteer?', a: 'Ja. Tag je bets met het toernooi, zoals "Premier League" of "WK". In de statistieken zie je je resultaat per tag.' },
      { q: 'Werkt de screenshot import voor dartsbets?', a: 'Ja. Upload een screenshot van je betslip en de AI leest de spelers, markt, odds en inzet uit.' },
      { q: 'Wat als een speler zich terugtrekt?', a: 'Wordt de bet ongeldig verklaard, kies dan de uitkomst Void. Je inzet telt dan niet mee in je resultaat.' },
    ],
    related: ['bets-bijhouden', 'statistieken', 'bets-importeren-met-ai'],
  },
  {
    slug: 'formule-1',
    sport: 'Formule 1',
    emoji: '🏎️',
    season: 'Maart – december',
    seasonNote: 'Zo\'n 24 Grands Prix plus sprintraces',
    name: 'Formule 1 bet tracker',
    title: 'Formule 1 bet tracker',
    metaTitle: 'Formule 1 bet tracker: F1 bets bijhouden',
    description:
      'Houd je Formule 1 bets bij: racewinnaar, podium, poleposition, head-to-heads en kampioenschap. Zie per markt of je winst maakt.',
    intro:
      'Formule 1 heeft zo\'n twintig races per seizoen, met markten van de racewinnaar tot onderlinge duels tussen teamgenoten. Omdat er veel minder evenementen zijn dan bij voetbal, telt elke bet zwaar mee. Met de Formule 1 bet tracker zie je per markt hoe je ervoor staat.',
    betTypes: [
      { emoji: '🏁', name: 'Racewinnaar', text: 'Wie wint de Grand Prix. Bij een dominante coureur lage odds, bij een open veld interessante waarde.' },
      { emoji: '🥉', name: 'Podium en top 6', text: 'Eindigt een coureur in de top 3, 6 of 10? Minder risico dan de winnaar, maar ook lagere odds.' },
      { emoji: '⏱️', name: 'Poleposition', text: 'Wie is de snelste in de kwalificatie. Een eigen markt waarin pure snelheid telt, niet racestrategie.' },
      { emoji: '🤜', name: 'Head-to-head', text: 'Welke van twee coureurs eindigt hoger. Vaak teamgenoten, en een markt waarin kennis van het team loont.' },
      { emoji: '⚡', name: 'Snelste ronde', text: 'Wie rijdt de snelste ronde van de race. Onvoorspelbaar door late pitstops voor verse banden.' },
      { emoji: '🚨', name: 'Safety car', text: 'Komt er een safety car in de race? Sterk afhankelijk van het circuit en het weer.' },
      { emoji: '💥', name: 'Uitvallers', text: 'Aantal coureurs dat de finish niet haalt, of valt een specifieke coureur uit.' },
      { emoji: '👑', name: 'Wereldkampioen', text: 'Kampioen bij de coureurs of constructeurs. Loopt het hele seizoen: registreer als Lopend.' },
    ],
    metrics: [
      { emoji: '🗺️', name: 'ROI per type circuit', text: 'Stratencircuits, snelle banen of klassiekers: tag je bets met het circuit en zie waar jouw inschattingen kloppen.' },
      { emoji: '🤜', name: 'Head-to-heads vs. winnaar', text: 'Head-to-heads zijn vaak voorspelbaarder. Vergelijk je rendement met je bets op de racewinnaar.' },
      { emoji: '🌧️', name: 'Natte races', text: 'Regen gooit alles door elkaar. Tag natte races en zie of je dan beter of slechter presteert.' },
      { emoji: '⏱️', name: 'Kwalificatie vs. race', text: 'Ben je beter in het voorspellen van de pole of van de race? Je statistieken per markt laten het zien.' },
      { emoji: '📅', name: 'Openstaande outrights', text: 'Houd bij hoeveel inzet er vastzit in kampioenschapsbets, zodat je bankroll klopt.' },
      { emoji: '🏎️', name: 'Sprint vs. Grand Prix', text: 'Sprintraces zijn korter en anders. Tag ze apart en vergelijk ze met je bets op de hoofdrace.' },
    ],
    tips: [
      { title: '🤜 Head-to-heads zijn onderschat', text: 'Teamgenoten rijden in dezelfde auto, dus het verschil zit in de coureur. Wie de onderlinge verhoudingen goed kent, vindt hier vaak meer waarde dan bij de racewinnaar. Houd bij of dat voor jou ook geldt.' },
      { title: '🏁 Wacht op de kwalificatie', text: 'Na de kwalificatie weet je veel meer over het tempo van de auto\'s. Odds voor de race veranderen dan snel. Vergelijk je bets van voor en na de kwalificatie en kijk welk moment het beste werkt.' },
      { title: '📅 Houd je lange-termijnbets bij', text: 'Een bet op de wereldkampioen wordt pas aan het eind van het seizoen afgerekend. Registreer zo\'n bet met de uitkomst Lopend en werk hem bij als het kampioenschap beslist is. Zo blijft je inzet zichtbaar in je overzicht.' },
    ],
    faq: [
      { q: 'Hoe houd ik een outright bet bij?', a: 'Voer de bet in met de uitkomst Lopend. Pas de uitkomst aan in je Bets Overzicht zodra de bet is afgerekend.' },
      { q: 'Kan ik head-to-heads bijhouden?', a: 'Ja. Kies de sport Formule 1, vul bij de markt "Head-to-head" in en als selectie de coureur die je hebt gekozen.' },
      { q: 'Kan ik sprintraces apart bekijken?', a: 'Ja. Geef je bets op sprintraces een tag, zoals "Sprint", en bekijk je resultaat per tag in de statistieken.' },
      { q: 'Wat gebeurt er als een coureur niet start?', a: 'Dat hangt af van de regels van je bookmaker. Wordt de bet ongeldig verklaard, kies dan de uitkomst Void.' },
      { q: 'Werkt de screenshot import voor F1-bets?', a: 'Ja. Upload een screenshot van je betslip en de AI leest de coureur, markt, odds en inzet uit.' },
    ],
    related: ['bets-bijhouden', 'dashboard', 'statistieken'],
  },
  {
    slug: 'wielrennen',
    sport: 'Wielrennen',
    emoji: '🚴',
    season: 'Februari – oktober',
    seasonNote: 'Klassiekers, Giro, Tour de France en Vuelta',
    name: 'Wielrennen bet tracker',
    title: 'Wielrennen bet tracker',
    metaTitle: 'Wielrennen bet tracker: wielerbets bijhouden',
    description:
      'Houd je wielerbets bij: ritwinnaar, eindklassement, head-to-heads en top 10. Van klassiekers tot de Tour de France.',
    intro:
      'Van de voorjaarsklassiekers tot de grote rondes: wielrennen biedt veel wedmogelijkheden, vaak met hoge odds. Daardoor zijn de schommelingen groot en is je gevoel een slechte graadmeter. Met de wielrennen bet tracker zie je welke koersen en markten je echt winst opleveren.',
    betTypes: [
      { emoji: '🥇', name: 'Ritwinnaar', text: 'Wie wint de etappe. Hoge odds, lage kans en dus grote schommelingen. Houd je inzet per bet klein.' },
      { emoji: '🏆', name: 'Eendagskoersen', text: 'Winnaar van een klassieker zoals de Ronde van Vlaanderen of Parijs-Roubaix. Parcours en weer bepalen alles.' },
      { emoji: '🟡', name: 'Eindklassement', text: 'Wie wint de Tour, Giro of Vuelta. Loopt drie weken: registreer als Lopend.' },
      { emoji: '🟢', name: 'Nevenklassementen', text: 'Puntentrui, bergtrui of jongerenklassement. Minder gespeeld en daardoor soms minder scherp geprijsd.' },
      { emoji: '🔟', name: 'Top 3 en top 10', text: 'Eindigt een renner bij de besten? Lagere odds dan de winnaar, maar veel vaker raak.' },
      { emoji: '🤜', name: 'Head-to-head', text: 'Welke van twee renners eindigt hoger. Een markt waarin je minder afhankelijk bent van het hele peloton.' },
      { emoji: '🚩', name: 'Beste landgenoot of ploeg', text: 'Beste Nederlander of welke ploeg wint de meeste ritten. Specials met eigen kansen.' },
      { emoji: '⛰️', name: 'Bergetappes', text: 'Bets op specifieke bergritten of de eerste boven op een col. Tag ze om ze apart te beoordelen.' },
    ],
    metrics: [
      { emoji: '📉', name: 'Max drawdown', text: 'Bij hoge odds kun je lang verliezen voordat één winnaar alles goedmaakt. Houd je grootste daling in de gaten.' },
      { emoji: '🗺️', name: 'ROI per type rit', text: 'Sprintritten, bergritten of tijdritten: tag je bets en zie waar jouw inschattingen het beste kloppen.' },
      { emoji: '🏆', name: 'Klassiekers vs. grote rondes', text: 'Vergelijk je resultaat op eendagskoersen met je bets in de grote rondes.' },
      { emoji: '🤜', name: 'Head-to-heads vs. winnaar', text: 'Head-to-heads hebben een veel hogere winkans. Kijk of ze je stabieler rendement opleveren.' },
      { emoji: '🎯', name: 'Hit rate', text: 'Hoe vaak raak je een ritwinnaar? Vergelijk je hit rate met je gemiddelde odds om te zien of het klopt.' },
      { emoji: '📅', name: 'Openstaande klassementsbets', text: 'Zie hoeveel inzet vastzit in het eindklassement, zodat je bankroll niet ongemerkt krimpt.' },
    ],
    tips: [
      { title: '📉 Reken op lange droge periodes', text: 'Bets op een ritwinnaar hebben vaak odds van 10 of hoger. Je kunt lange tijd verliezen en dan met één winnende bet alles terugwinnen. Kijk daarom niet alleen naar je winst, maar ook naar je max drawdown in de statistieken, en houd je inzet per bet klein.' },
      { title: '🗺️ Bestudeer het parcours', text: 'Een vlakke rit, een aankomst bergop of een waaierrit vraagt om compleet andere renners. Wie het parcours kent, schat de kansen beter in dan de massa. Tag je bets met het type rit en zie of dat werkt.' },
      { title: '🤜 Gebruik head-to-heads als basis', text: 'Head-to-heads geven een rustiger verloop dan bets op de winnaar. Veel wedders gebruiken ze als basis en zetten klein in op ritwinnaars. Je tracker laat zien of die mix voor jou werkt.' },
    ],
    faq: [
      { q: 'Kan ik bets op het eindklassement bijhouden?', a: 'Ja. Voer ze in met de uitkomst Lopend en werk ze bij na de laatste etappe.' },
      { q: 'Wat als een renner niet start?', a: 'Dat hangt af van de regels van je bookmaker. Wordt de bet ongeldig verklaard, kies dan de uitkomst Void.' },
      { q: 'Kan ik zien welk type rit mij het beste ligt?', a: 'Ja. Tag je bets met bijvoorbeeld "Sprint", "Berg" of "Tijdrit" en bekijk je resultaat per tag in de statistieken.' },
      { q: 'Wat is max drawdown?', a: 'De grootste daling van je saldo vanaf een hoogtepunt. Bij wielrennen met hoge odds is dat een belangrijke maat om je risico te beoordelen.' },
      { q: 'Werkt de screenshot import voor wielerbets?', a: 'Ja. Upload een screenshot van je betslip en de AI leest de renner, markt, odds en inzet uit.' },
    ],
    related: ['statistieken', 'units-en-export', 'bets-bijhouden'],
  },
  {
    slug: 'hockey',
    sport: 'Hockey',
    emoji: '🏒',
    season: 'Oktober – juni',
    seasonNote: 'NHL, KHL en de Hoofdklasse hockey',
    name: 'Hockey bet tracker',
    title: 'Hockey bet tracker',
    metaTitle: 'Hockey bet tracker: hockeybets bijhouden',
    description:
      'Houd je hockeybets bij, van ijshockey (NHL) tot veldhockey: winnaar, handicap (puck line), totaal aantal goals en periodes. Zie per markt je rendement.',
    intro:
      'Hockey is een snelle sport met relatief weinig doelpunten, waardoor kleine verschillen in odds en lijnen veel uitmaken. Of je nu op ijshockey of veldhockey wedt: met de hockey bet tracker zie je welke markten je winst opleveren.',
    betTypes: [
      { emoji: '🏆', name: 'Moneyline', text: 'Winnaar inclusief verlenging en shoot-outs. De meest gespeelde markt bij de NHL.' },
      { emoji: '⏱️', name: '1X2 reguliere speeltijd', text: 'Winnaar na 60 minuten, met gelijkspel als optie. Hogere odds dan de moneyline.' },
      { emoji: '➖', name: 'Puck line', text: 'De hockeyhandicap, meestal -1.5 of +1.5. Een favoriet moet met twee doelpunten verschil winnen.' },
      { emoji: '🔢', name: 'Totaal aantal goals', text: 'Over/Under, vaak rond 5.5 of 6.5. Keepers en speelstijl bepalen de lijn.' },
      { emoji: '🧊', name: 'Periodes', text: 'Winnaar of total per periode. Handig als je een sterke start of een late comeback verwacht.' },
      { emoji: '🤝', name: 'Beide teams scoren', text: 'Scoren beide teams? Een eenvoudige markt die bij hockey vaak raak is, maar lage odds heeft.' },
      { emoji: '🥅', name: 'Player props', text: 'Goals, assists, schoten op doel of saves van de keeper. Houd per type bij hoe je scoort.' },
      { emoji: '📅', name: 'Futures', text: 'Stanley Cup-winnaar of kampioen van de Hoofdklasse. Registreer als Lopend.' },
    ],
    metrics: [
      { emoji: '⏱️', name: 'Moneyline vs. 60 minuten', text: 'Vergelijk je bets inclusief verlenging met je 1X2-bets op de reguliere speeltijd.' },
      { emoji: '🥅', name: 'Invloed van de keeper', text: 'De startende keeper verandert de odds sterk. Tag je bets op keeperskeuze en zie of dat loont.' },
      { emoji: '🏒', name: 'IJshockey vs. veldhockey', text: 'Twee compleet verschillende sporten. Tag ze apart en zie in welke je het beste presteert.' },
      { emoji: '➖', name: 'Puck line vs. moneyline', text: 'Leg je liever -1.5 op een favoriet of pak je de moneyline? Je statistieken laten zien wat beter werkt.' },
      { emoji: '📈', name: 'Favoriet vs. underdog', text: 'Hockey kent veel verrassingen. Kijk of je ROI hoger is op underdogs.' },
      { emoji: '😴', name: 'Back-to-backs', text: 'NHL-teams die twee avonden op rij spelen, zetten vaak hun tweede keeper op. Tag die bets en vergelijk.' },
    ],
    tips: [
      { title: '⏱️ Let op: met of zonder verlenging', text: 'Bij ijshockey maakt het veel uit of een markt wordt afgerekend op de reguliere speeltijd of inclusief verlenging en shoot-outs. Vermeld dat in je markt of met een tag, zodat je in je statistieken ziet welke variant voor jou beter werkt.' },
      { title: '🥅 Check de keeper voordat je wedt', text: 'Geen enkele speler heeft zoveel invloed als de keeper. Wacht met je bet tot bekend is wie er in de goal staat. Houd bij of je bets met die informatie beter scoren.' },
      { title: '📈 Durf underdogs te spelen', text: 'Door de weinige doelpunten en de rol van geluk winnen underdogs bij hockey relatief vaak. Je tracker laat zien of je rendement op underdogs beter is dan op favorieten.' },
    ],
    faq: [
      { q: 'Hoe houd ik een 1X2-bet op ijshockey bij?', a: 'Kies de sport Hockey en de markt 1X2. Vermeld in de selectie of notitie dat het om de reguliere speeltijd gaat.' },
      { q: 'Wat is de puck line?', a: 'De handicap bij ijshockey, meestal -1.5 voor de favoriet en +1.5 voor de underdog. Kies de markt Handicap om hem bij te houden.' },
      { q: 'Kan ik ijshockey en veldhockey apart bekijken?', a: 'Ja. Geef je bets een tag, zoals "NHL" of "Hoofdklasse", en bekijk je resultaat per tag in de statistieken.' },
      { q: 'Hoe houd ik een Stanley Cup-bet bij?', a: 'Voer de bet in met de uitkomst Lopend en werk hem bij na de finale.' },
      { q: 'Werkt de screenshot import voor hockeybets?', a: 'Ja. Upload een screenshot van je betslip en de AI leest de teams, markt, odds en inzet uit.' },
    ],
    related: ['statistieken', 'bets-bijhouden', 'odds-vergelijker'],
  },
  {
    slug: 'snooker',
    sport: 'Snooker',
    emoji: '🎱',
    season: 'Juli – mei',
    seasonNote: 'WK in Sheffield, UK Championship en Masters',
    name: 'Snooker bet tracker',
    title: 'Snooker bet tracker',
    metaTitle: 'Snooker bet tracker: snookerbets bijhouden',
    description:
      'Houd je snookerbets bij: winnaar, frame handicap, totaal aantal frames, correcte score en century breaks. Zie per toernooi hoe je presteert.',
    intro:
      'Snooker kent lange toernooien met veel wedstrijden, van korte partijen tot WK-finales over 35 frames. Met de snooker bet tracker houd je al je snookerbets bij en zie je bij welke formats en markten je voorsprong zit.',
    betTypes: [
      { emoji: '🏆', name: 'Wedstrijdwinnaar', text: 'Wie wint de partij. De meest gespeelde snookermarkt, met grote verschillen per format.' },
      { emoji: '➖', name: 'Frame handicap', text: 'Een speler krijgt frames voor of achter, zoals -2.5. Interessant bij grote niveauverschillen.' },
      { emoji: '🔢', name: 'Totaal aantal frames', text: 'Over/Under op het aantal frames. Hangt af van hoe gelijkwaardig de spelers zijn.' },
      { emoji: '🎯', name: 'Correcte score', text: 'De exacte uitslag in frames. Hoge odds, lage kans: houd ze apart bij.' },
      { emoji: '💯', name: 'Century breaks', text: 'Aantal breaks van 100 of meer in de partij. Populair bij aanvallende spelers.' },
      { emoji: '⭐', name: 'Hoogste break', text: 'Hoogste break van de partij of van het toernooi. Grote schommelingen, dus klein inzetten.' },
      { emoji: '🥇', name: 'Eerste frame', text: 'Wie wint het eerste frame. Een korte markt met veel toeval.' },
      { emoji: '🏅', name: 'Toernooiwinnaar', text: 'Outright op de winnaar van het WK of de Masters. Registreer als Lopend tot de finale.' },
    ],
    metrics: [
      { emoji: '📏', name: 'Kort vs. lang format', text: 'Best of 7 is veel onvoorspelbaarder dan best of 19. Tag je bets met de lengte van de partij.' },
      { emoji: '🏟️', name: 'ROI per toernooi', text: 'Ranking events, Triple Crown of invitationals: zie per toernooi waar je het beste presteert.' },
      { emoji: '💯', name: 'Specials vs. winnaar', text: 'Vergelijk je bets op century breaks en hoogste break met je bets op de winnaar.' },
      { emoji: '📈', name: 'Favoriet vs. underdog', text: 'Kijk of je rendement hoger is op de grote namen of op de onbekende uitdagers.' },
      { emoji: '🧮', name: 'Gemiddelde odds', text: 'Een hoge win rate op favorieten met lage odds is niet automatisch winst. Houd je gemiddelde odds in de gaten.' },
      { emoji: '🏦', name: 'Resultaat per bookmaker', text: 'Snookermarkten worden per bookmaker verschillend geprijsd. Zie waar je het meeste rendement haalt.' },
    ],
    tips: [
      { title: '📏 Korte partijen, grote verrassingen', text: 'Hoe korter de partij, hoe groter de kans op een verrassing. Tag je bets met de lengte van de wedstrijd (bijvoorbeeld "best of 7" of "best of 19") en zie in je statistieken bij welke formats je het beste presteert.' },
      { title: '🔋 Let op vorm en vermoeidheid', text: 'Snookertoernooien volgen elkaar snel op en spelers reizen veel. Een speler die net een lange finale heeft gespeeld, begint soms slap aan het volgende toernooi. Houd bij of bets op die momenten beter uitpakken.' },
      { title: '💯 Ken je spelers bij breaks-markten', text: 'Sommige spelers maken bijna elke partij een century, anderen spelen vooral safe. Wie de speelstijl kent, vindt waarde in de breaks-markten. Je tracker laat zien of dat klopt.' },
    ],
    faq: [
      { q: 'Kan ik bets op century breaks bijhouden?', a: 'Ja. Kies de sport Snooker, vul bij de markt "Century breaks" in en je selectie, bijvoorbeeld "Over 2.5".' },
      { q: 'Hoe houd ik een WK-winnaar bet bij?', a: 'Voer de bet in met de uitkomst Lopend en werk hem bij na de finale in Sheffield.' },
      { q: 'Kan ik zien bij welk format ik het beste presteer?', a: 'Ja. Tag je bets met bijvoorbeeld "Best of 7" of "Best of 19" en bekijk je resultaat per tag in de statistieken.' },
      { q: 'Wat als een speler zich terugtrekt?', a: 'Wordt de bet ongeldig verklaard, kies dan de uitkomst Void. Je inzet telt dan niet mee in je resultaat.' },
      { q: 'Werkt de screenshot import voor snookerbets?', a: 'Ja. Upload een screenshot van je betslip en de AI leest de spelers, markt, odds en inzet uit.' },
    ],
    related: ['bets-bijhouden', 'statistieken', 'bets-importeren-met-ai'],
  },
  {
    slug: 'american-football',
    sport: 'American Football',
    emoji: '🏈',
    season: 'September – februari',
    seasonNote: 'NFL, playoffs, Super Bowl en college football',
    name: 'American football bet tracker',
    title: 'American football bet tracker',
    metaTitle: 'NFL bet tracker: American football bets bijhouden',
    description:
      'Houd je American football bets bij: moneyline, point spread, totals en player props. Van NFL tot college football, met je rendement per markt.',
    intro:
      'Ook in Nederland wordt steeds meer op de NFL gewed. De markten draaien vooral om spreads en totals, met odds rond de 1.90. Met maar 17 wedstrijden per team per seizoen telt elke bet. Met de American football bet tracker zie je of jouw bets op lange termijn winst opleveren.',
    betTypes: [
      { emoji: '🏆', name: 'Moneyline', text: 'Welk team wint, inclusief overtime. Bij grote favorieten lage odds, bij underdogs soms veel waarde.' },
      { emoji: '📏', name: 'Point spread', text: 'De handicap, zoals -3.5. De belangrijkste NFL-markt. Let op key numbers zoals 3 en 7.' },
      { emoji: '🔢', name: 'Totals', text: 'Over/Under op het totaal aantal punten. Weer, wind en blessures hebben veel invloed.' },
      { emoji: '🏃', name: 'Player props', text: 'Passing yards, rushing yards, receptions of touchdowns. Een enorme markt met veel keuze.' },
      { emoji: '🙌', name: 'Touchdown scorers', text: 'Eerste of op elk moment scorende speler. Hoge odds, dus klein inzetten en goed bijhouden.' },
      { emoji: '⏱️', name: 'Helften en kwarten', text: 'Spread of total per helft of kwart. Handig als je een snelle start of een sterke tweede helft verwacht.' },
      { emoji: '🔀', name: 'Teasers en parlays', text: 'Combinaties of aangepaste spreads. Hogere marge, dus houd ze apart bij.' },
      { emoji: '🏟️', name: 'Futures', text: 'Super Bowl-winnaar, MVP of aantal overwinningen. Registreer als Lopend tot het einde van het seizoen.' },
    ],
    metrics: [
      { emoji: '🎯', name: 'Win rate op spreads', text: 'Bij odds van 1.90 heb je ruim 52,6% nodig om quitte te spelen. Zie of je daar structureel boven zit.' },
      { emoji: '🔑', name: 'Key numbers', text: 'Veel NFL-wedstrijden eindigen met 3 of 7 punten verschil. Houd bij welke spreads je pakt rond die getallen.' },
      { emoji: '🏈', name: 'NFL vs. college', text: 'College football wordt minder scherp geprijsd. Tag je bets en vergelijk je resultaat.' },
      { emoji: '🏃', name: 'ROI per type prop', text: 'Ben je beter in passing yards dan in touchdowns? Houd het prop-type bij in je markt.' },
      { emoji: '🌬️', name: 'Weer en totals', text: 'Wind en regen drukken de score. Tag bets in slecht weer en zie of je er voordeel uit haalt.' },
      { emoji: '📅', name: 'Resultaat per speelweek', text: 'Zie in je maandoverzicht hoe je seizoen verloopt en of je in de loop van het jaar beter wordt.' },
    ],
    tips: [
      { title: '🔑 Ken de key numbers', text: 'Omdat punten vaak per 3 (field goal) of 7 (touchdown) komen, eindigen veel wedstrijden met precies dat verschil. Een spread van -2.5 is dus veel meer waard dan -3.5. Vergelijk lijnen tussen bookmakers en houd bij welke spreads je pakt.' },
      { title: '🏥 Volg de injury reports', text: 'Het uitvallen van een quarterback verschuift de lijn met punten. Wie het blessurenieuws snel verwerkt, vindt waarde voordat de odds zijn aangepast. Tag bets die je op nieuws plaatst en kijk of dat loont.' },
      { title: '🧮 Kleine marges, grote verschillen', text: 'Bij odds van 1.90 heb je een win rate van ruim 52,6% nodig om quitte te spelen. Een halve punt verschil in de spread kan het verschil maken tussen winst en verlies. Je tracker laat zien of je aan de goede kant van die grens zit.' },
    ],
    faq: [
      { q: 'Kan ik player props bijhouden?', a: 'Ja. Vul bij de markt het type prop in, zoals "Passing yards", en je selectie, bijvoorbeeld "Over 249.5".' },
      { q: 'Telt overtime mee?', a: 'Bij de meeste NFL-markten wel, maar controleer de regels van je bookmaker. Voer de uitkomst in zoals de bookmaker die afrekent.' },
      { q: 'Hoe houd ik een push bij?', a: 'Eindigt de spread precies op de lijn, dan krijg je je inzet terug. Kies dan de uitkomst Void of Push.' },
      { q: 'Hoe houd ik een Super Bowl-bet bij?', a: 'Voer de bet in met de uitkomst Lopend en werk hem bij na de Super Bowl.' },
      { q: 'Kan ik NFL en college football apart bekijken?', a: 'Ja. Geef je bets een tag, zoals "NFL" of "NCAA", en bekijk je resultaat per tag in de statistieken.' },
    ],
    related: ['odds-vergelijker', 'statistieken', 'calculators'],
  },
  {
    slug: 'baseball',
    sport: 'Baseball',
    emoji: '⚾',
    season: 'Maart – oktober',
    seasonNote: 'MLB regular season, playoffs en World Series',
    name: 'Baseball bet tracker',
    title: 'Baseball bet tracker',
    metaTitle: 'Baseball bet tracker: MLB bets bijhouden',
    description:
      'Houd je baseballbets bij: moneyline, run line, totals en first five innings. Zie per markt of je winst maakt op de MLB.',
    intro:
      'Met 2.430 wedstrijden in het MLB-seizoen en bijna elke dag wedstrijden is baseball de sport waarin je de meeste bets plaatst. De startende pitchers bepalen veel van de uitslag. Met de baseball bet tracker zie je per markt waar je winst of verlies maakt, en of het geluk of kunde is.',
    betTypes: [
      { emoji: '🏆', name: 'Moneyline', text: 'Welk team wint. De belangrijkste baseballmarkt. Houd je resultaat per startende pitcher, team en thuis/uit bij.' },
      { emoji: '➖', name: 'Run line', text: 'De honkbalhandicap, meestal -1.5 of +1.5. Een favoriet moet met twee runs verschil winnen.' },
      { emoji: '🔢', name: 'Totals', text: 'Over/Under op het aantal runs. Pitchers, stadion, wind en temperatuur bepalen de lijn.' },
      { emoji: '5️⃣', name: 'First five innings (F5)', text: 'Alleen de eerste vijf innings, zonder invloed van de bullpen. Ideaal als je pitchers goed kunt inschatten.' },
      { emoji: '⚡', name: 'Player props', text: 'Strikeouts van de pitcher, hits, home runs of total bases. Een grote markt met veel keuze.' },
      { emoji: '🏟️', name: 'Team totals', text: 'Het aantal runs van één team. Handig als je een aanval of pitcher goed kunt inschatten.' },
      { emoji: '📆', name: 'Series bets', text: 'Wie wint de serie van drie of vier wedstrijden. Spreidt het risico over meerdere dagen.' },
      { emoji: '🏅', name: 'Futures', text: 'World Series-winnaar, divisie of Cy Young. Registreer als Lopend tot het einde van het seizoen.' },
    ],
    metrics: [
      { emoji: '⚾', name: 'Resultaat per startende pitcher', text: 'Tag je bets met de pitcher. Zo zie je bij welke pitchers je inschatting klopt en welke je beter kunt mijden.' },
      { emoji: '5️⃣', name: 'F5 vs. hele wedstrijd', text: 'Veel wedders winnen op F5 maar verliezen op de hele wedstrijd door de bullpen. Houd ze apart bij.' },
      { emoji: '🏟️', name: 'Invloed van het stadion', text: 'Coors Field is iets heel anders dan een pitchersstadion. Tag je totals met het stadion en vergelijk.' },
      { emoji: '🏠', name: 'Thuis vs. uit', text: 'Het thuisvoordeel is bij baseball kleiner dan bij andere sporten. Kijk of je er te veel op leunt.' },
      { emoji: '🐶', name: 'ROI op underdogs', text: 'Baseball is dé sport voor underdogs: elk team kan elke dag winnen. Zie of je underdogbets winst opleveren.' },
      { emoji: '🌬️', name: 'Weer en totals', text: 'Wind en temperatuur beïnvloeden het aantal runs. Tag bets met extreem weer en zie of je er voordeel uit haalt.' },
    ],
    tips: [
      { title: '⚾ Pitcheronderzoek is onmisbaar', text: 'Baseball is de sport waarin één speler de meeste invloed heeft: de startende pitcher. Noteer bij elke bet wie er pitcht. Na een tijdje zie je patronen, bijvoorbeeld dat je goed bent in het herkennen van overschatte toppers. Je tracker maakt van dat onderzoek meetbare resultaten.' },
      { title: '5️⃣ De F5-markt is scherper dan je denkt', text: 'F5-bets zijn populair omdat ze de onvoorspelbare bullpen weglaten. Maar bookmakers prijzen F5-lijnen juist zorgvuldig. Houd je F5-resultaten apart bij en vergelijk ze met je bets op de hele wedstrijd. Win je F5 maar verlies je de hele wedstrijd? Dan weet je wat je moet doen.' },
      { title: '📊 Volg waarde, niet verhalen', text: 'Media maken graag verhalen van reeksen, slumps en sterke stadions. Bookmakers verwerken die verhalen in hun odds. Tag je bets op een verhaal en je bets op data, en kijk welke groep echt wint.' },
    ],
    faq: [
      { q: 'Wat gebeurt er als een wedstrijd wordt uitgesteld?', a: 'Wordt de bet door de bookmaker ongeldig verklaard, kies dan de uitkomst Void. Je inzet telt dan niet mee in je resultaat.' },
      { q: 'Hoe houd ik bets bij met pitcherinformatie?', a: 'Geef je bet een tag met de naam van de startende pitcher. In de statistieken zie je dan je resultaat per pitcher.' },
      { q: 'Moet ik F5-bets apart bijhouden?', a: 'Ja, dat is aan te raden. Kies bij de markt "First 5 innings" of geef ze een tag "F5". Zo vergelijk je ze eenvoudig met je bets op de hele wedstrijd.' },
      { q: 'Wat als de startende pitcher wordt gewijzigd?', a: 'Sommige bookmakers verklaren de bet dan ongeldig, andere niet. Voer de uitkomst in zoals de bookmaker die afrekent.' },
      { q: 'Hoeveel baseballbets moet ik bijhouden?', a: 'Hoe meer, hoe beter. Met zoveel wedstrijden heb je snel een paar honderd bets. Pas dan zegt je ROI echt iets over je kunde.' },
    ],
    related: ['statistieken', 'bets-bijhouden', 'odds-vergelijker'],
  },
];

export const getSportPage = (slug) => SPORT_PAGES.find(s => s.slug === slug);
